name: pedidos_app
description: Aplicacion de gestión de pedidos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  flutter_contacts: ^1.1.7
  shared_preferences: ^2.2.2
