name: pedidos_app
description: Aplicacion de gestión de pedidos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  excel: ^4.0.3        # Para leer el archivo .xlsx
  file_picker: ^8.0.0  # Para abrir el explorador y seleccionar el archivo
